# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: end2end
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://nandomoreira.me
baseurl: "/varoonbehramsha"
# baseurl: ""

# google_analytics: UA-52446115-1
repo: http://github.com/nandomoreirame/end2end
disqus_shortname: "nandothemes"
disqus_site_shortname: "nandothemes"

# Author settings
author:
  name      : Varoon Behramsha
  job       : iOS Developer
  bio       : "Wise is not he who has wisdom, but he who knows how to apply his wisdom"
  thumb     : /images/author.jpg
  email     : varoonbehramsha@gmail.com
  url       : http://varoonbehramsha.com
  github    : http://github.com/varoonbehramsha
  twitter   : http://twitter.com/varoonbehramsha
  facebook  : http://facebook.com/varoonbehramsha
  linkedin  : http://linkedin.com/in/varoon-behramsha-7491048a

# navbar pages
navbar:
  - slug: About
    title: About
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  - slug: Blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
